name: Reusable workflow user

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run one line script Reusable workflow user
        run: echo This is resuable workflow user
      - name: Play with variables
        run: |
          pd=pwd
        id: getvalue
      - name: display vars
        run : echo "The value is : ${{ steps.getvalue.pd }}"

  run-resuable-flow:
    uses: rushikeshshelke/ReusableWorkflow/.github/workflows/welcomeFlow.yml@main
