name: Reusable workflow user

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: 1.2.3
  TENANT: Rushikesh

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run one line script Reusable workflow user
        run: echo This is resuable workflow user
      - name: Play with variables
        run: |
          pwd
          ls
      - name: display env vars
        run: |
          echo "Test-Project: ${{ env.VERSION }}"
          echo "Test-Project: ${{ env.TENANT }}"

  run-resuable-flow:
    uses: rushikeshshelke/ReusableWorkflow/.github/workflows/welcomeFlow.yml@main
    with:
      VERSION: env.VERSION
      TENANT: Rushikesh
