name: Reusable workflow user

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      VERSION:
        required: true
        default: 1.4.5
        type: string

env:
  VERSION: 1.2.3
  TENANT: Rushikesh

jobs:
  doit:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/checkout@v2

      - name: Run one line script Reusable workflow user
        run: echo This is resuable workflow user
      - name: Play with variables
        run: |
          pwd
          ls
      - name: display env vars
        run: |
          echo "Test-Project: ${{ env.VERSION }}"
          echo "Test-Project: ${{ env.TENANT }}"
      - id: step1
        run: echo "::set-output name=test::${{ env.VERSION }}"
      - name: run external sh file
        run : ./scripts/test.sh

  run-resuable-flow:
    needs: doit
    uses: rushikeshshelke/ReusableWorkflow/.github/workflows/welcomeFlow.yml@main
    with:
      VERSION: ${{ needs.doit.outputs.output1 }}
      TENANT: Rushikesh
